default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: nri2023_development

test:
  <<: *default
  database: nri2023_test

production:
  <<: *default
  database: nri2023_production